version: '3.1'

services:
  database:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: some_secret_password
    ports:
      - 3306:3306
    volumes:
      - "../var/mysql:/var/lib/mysql"

